name: Docker Image CI

on:
  push:
    branches: [ "onnx" ]
  pull_request:
    branches: [ "onnx" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ocr_lite:$(date +%s)
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: cex-trader/chineseocr_lite/chineseocr-lite
        tag_with_ref: true
